language: java
sudo: true
dist: trusty
jdk: oraclejdk9
addons:
  apt:
    packages:
      - oracle-java9-installer
before_install:
  - chmod +x mvnw
#language: java
#jdk: oraclejdk9
#install: true
#script: ./mvnw clean install

